#!/bin/bash


# given a room number will generate
# the art cards for the number of images in it
# need to paste into index.html

(( $# < 1 )) && echo "Usage: $0 <room-number>" && exit 1

>&2 echo "Assumes you are running from within rooms dir"

room=$1

i=0
for f in $(find $room -name "*.jpg"); do
  (( i++ ))
  istr=$(printf "%03d" $i)

cat <<CARD
                <article class="art-card" 
                         onclick="openLightbox('rooms/${room}/${istr}.jpg')" 
                         data-title-src="rooms/${room}/${istr}_title.txt" 
                         data-details-src="rooms/${room}/${istr}_details.txt">
                    <img src="rooms/${room}/${istr}.jpg" width="256" alt="thumbnail">
                    <div class="art-info">
                        <!-- Left blank; JavaScript will populate this dynamically -->
                        <h2 class="art-title">Loading...</h2>
                        <p class="art-details"></p>
                    </div>
                </article>
CARD

done
