#!/bin/bash

>&2 echo "assumes you are running from within a room dir"

room=0
for rname in abstract scenes trees flowers still-life various photos; do
  (( room++ ))
  rstr=$(printf "%02d" $room)
  cd ../${room}
  i=0
  for f in $(find ../../images/${rname} -name "*.jpg"); do
    (( i++ ))
    istr=$(printf "%03d" $i)
    ln -sfn ${f} ${i}.jpg
    bf=${f//.jpg/}
    for w in title details; do
      ln -sfn ${bf}_${w}.txt ${istr}_${w}.txt
    done
  done
done
